[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

board_build.filesystem = littlefs
board_build.filesystem_size = 1m

upload_port = E:/

build_type = debug

lib_deps =
  https://github.com/vicharak-in/shrike_arduino.git
